### ISSUE TITLE
What System Support?

### ISSUE THREAD

**Issue by QuestionPython** [VladimirMarkelov/utf8string#2]
Hello,
raspberry pi Microcontroller and Windows (server,xp,7,8,10) support? @VladimirMarkelov

**Comment by questionpython** [comment]
@VladimirMarkelov

**Comment by VladimirMarkelov** [comment]
Hi,
Initially I developed the library on Windows. 
At the same time the library compiles without any issue on Ubuntu: 
%cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
build(master) %make
.....
[100%] Built target utf8test
% cd tests
%./utf8test
......
Tests run: 20
Success: 20
Fail: 0

Sorry, I do not have raspberry pi and cannot test
